Sdk6toast
R2bEEaton/njit-pending-cs490 pull request #11
Opened 2023-10-30 20:48 UTC by Sdk6

2023-10-30 22:16 UTC, R2bEEaton requested changes
Right now the toast shows up all the time, but it should only show up on HomePage right after a login. Similarly, it should take you back to LoginPage and play a toast with an error if the login fails. Check my other comment for details.

2023-10-30 22:16 UTC, R2bEEaton commented on web/src/pages/HomePage/HomePage.jsx
> +  toast.success(`Login successful, welcome ${currentUser.email}`)
Here the toast is always played whenever a user visits that page. This means any time they refresh they will see the same toast. We only want it to happen right after they log in. Check this example for creating a dynamic toast, and the ability to add more readable error messages to oauth.js: https://redwoodjs.com/docs/how-to/oauth#better-error-handling

2023-10-31 07:04 UTC, Sdk6 commented
i changed to show toast on the first login but im not sure how a google login fails, wouldnt they just automatically go back to login? I am going to sleep now but am happy to talk more about this later.

2023-10-31 14:08 UTC, R2bEEaton commented
What you have there looks great for showing the message on first login! As for showing login errors, you are right. Most of the login errors are caught by Google. But we get some of them.

Look in /api/src/functions/oauth/oauth.js
Line 37
Line 53

Both of these catch potential errors with the login. They currently just return an error message, but you should make them redirect back to routes.login() and show a toast with that error message.

2023-11-09 02:48 UTC, R2bEEaton commented
Merged as part of #15 I think

2023-11-09 02:48 UTC, closed without merging